linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - gomnd
    - lll
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - prealloc
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
    - wastedassign
    - gochecknoglobals

linters-settings:
  gosec:
    excludes:
      - G101
  gocritic:
    disabled-checks:
      - "ifElseChain"
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  nlreturn:
    block-size: 4
  govet:
    check-shadowing: false
  nolintlint:
    require-explanation: true
    require-specific: true
  wsl:
    allow-cuddle-declarations: true
    force-err-cuddling: true
    allow-assign-and-anything: true
  gocognit:
    min-complexity: 160

run:
  timeout: 5m
