// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"medicine/examination/delivery/front"
	"medicine/examination/repository/postgres"
	"medicine/examination/usecase"
	postgres2 "medicine/prescription/repository/postgres"
)

// Injectors from wire.go:

func InitializeExaminationFront(pool *pgxpool.Pool) *front.Examination {
	examinationRepository := postgres.NewExamination(pool)
	prescriptionRepository := postgres2.NewPrescription(pool)
	examinationUseCase := usecase.NewExamination(examinationRepository, prescriptionRepository)
	examination := front.NewExamination(examinationUseCase)
	return examination
}
