name: Go App

on:
  push:
    branches:
      - 'feature/*'

jobs:
  vet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: Run vet
        run: |
          go vet ./...
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: |
          golangci-lint run ./... -v --config .golangci.yml

  tests:
    runs-on: ubuntu-latest
    needs:
      - vet
      - lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: Run tests
        run: |
          go test -cover ./... -v

  build:
    runs-on: ubuntu-latest
    needs:
      - tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'
      - name: Build Go application
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o my-app ./app/main.go

  trivy_code:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan for vulnerabilities in Go dependencies
        run: |
          trivy fs --exit-code 1 --severity CRITICAL,HIGH,MEDIUM --no-progress .

  trivy_docker_image:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image for vulnerabilities (optional)
        run: |
          docker build --build-arg APP_NAME=medicine -f ./ci/dockerfiles/api -t trivy-go-app .
          trivy image --exit-code 1 --severity CRITICAL,HIGH trivy-go-app
